<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OnlineExamer.Data\OnlineExamer.Data.csproj" />
    <ProjectReference Include="..\OnlineExamer.Infrastructure\OnlineExamer.Infrastructure.csproj" />
  </ItemGroup>

</Project>
